#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Span {
    pub start: u32,
    pub end: u32,
    pub file_id: u16,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kw {
    Never,
    SelfKw,
    Sized,
    Addrspace,
    As,
    Async,
    Await,
    BareMetal,
    Bf16,
    Bool,
    Break,
    Byte,
    Cap,
    Catch,
    Char,
    Const,
    Continue,
    Dec128,
    Dec32,
    Dec64,
    Defer,
    Distributed,
    Dyn,
    Effect,
    Else,
    Enum,
    Ensure,
    Extern,
    F128,
    F16,
    F32,
    F64,
    False,
    Fn,
    For,
    Hosted,
    I128,
    I16,
    I32,
    I64,
    I8,
    If,
    Impl,
    In,
    Is,
    Isolate,
    Isize,
    Let,
    Loop,
    Macro,
    Managed,
    Match,
    Mod,
    Module,
    Move,
    Mut,
    Not,
    Opaque,
    Override,
    Package,
    Panic,
    Parallel,
    Persistent,
    Pub,
    Pure,
    Ref,
    Relation,
    Require,
    Return,
    Script,
    SelfRef,
    Static,
    Str,
    Struct,
    Super,
    ThreadLocal,
    Trait,
    True,
    Try,
    Type,
    Typeof,
    U128,
    U16,
    U32,
    U64,
    U8,
    Unsafe,
    Use,
    Usize,
    Verified,
    Where,
    While,
    With,
    Yield,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Punct {
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    Eq,
    EqEq,
    NotEq,
    Lt,
    Le,
    Gt,
    Ge,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Colon,
    ColonColon,
    Semicolon,
    Arrow,
    FatArrow,
    Amp,
    AmpAmp,
    Pipe,
    PipePipe,
    PipeArrow,
    Bang,
    Dot,
    DotDot,
    DotDotEq,
    Question,
    QuestionDot,
    QuestionQuestion,
    At,
    Hash,
    Dollar,
    Underscore,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenKind {
    Ident,
    Int,
    Float,
    Char,
    String,
    RawString,
    Keyword(Kw),
    Punct(Punct),
    Indent,
    Dedent,
    Error,
    /// Terminal token emitted after the last real token.
    ///
    /// It carries the zero-width span at end of input plus any trivia that
    /// follows the final token, which is what lets consumers reconstruct the
    /// source byte-for-byte instead of dropping the tail of the file.
    Eof,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TriviaKind {
    Whitespace,
    LineComment,
    BlockComment,
    DocComment,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Trivia {
    pub kind: TriviaKind,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    pub leading_trivia: Vec<Trivia>,
    pub trailing_trivia: Vec<Trivia>,
}

// Trivia preservation (lossless CST) behavior lives here. No `implements` tag is
// claimed: LEX-0002 is Superseded under the Candidate-2 amendment, so the prior
// ownership tag was stale linkage and was removed by the reaper. Re-ownership
// awaits a surviving normative rule ID from the specification layer.
