//! SRC-0006 - bidi controls and invisible format characters in comments.
//!
//! SRC-0006 reads, verbatim from `spec/registry/rule-texts.json`:
//!
//! > Inside comments, bidi controls and invisible format characters require an
//! > escaped visible annotation generated by the formatter; strict mode
//! > rejects unannotated occurrences.
//!
//! # The rule
//!
//! Inside a comment these characters are *data*, not source: SRC-0005 stops
//! applying and SRC-0007 does not apply either, so a bidi control in a comment
//! is legal to lex but must not be invisible to a human reader. The rule
//! resolves that by requiring a visible escaped annotation of the same code
//! point, and by having strict mode reject any unannotated occurrence.
//!
//! # Why the escape reuses LEX-0007
//!
//! SRC-0006 requires "an escaped visible annotation" but does not fix its
//! syntax, so the implementation must choose one. It reuses the existing
//! normative `escape_sequence` production from LEX-0007 -- `\u{H...}` -- rather
//! than inventing a second, parallel notation. That keeps the surface
//! language closed (the repository's own policy: no new productions without
//! specification authority), makes the annotation unambiguous against an
//! adjacent literal backslash, and means a formatter can emit it using
//! machinery it already needs.
//!
//! Because that syntax choice is a genuine gap in the normative text rather
//! than an implementation convenience, it is recorded through the repository's
//! established erratum/specification process rather than being silently
//! chosen here; see `docs/foundation-gates.md` and ADR-0002.
//!
//! # What is never done
//!
//! These characters are never discarded, never replaced with U+FFFD, and never
//! dropped from the comment's byte span. A comment containing them round-trips
//! byte-for-byte, and [`annotate_comment`] is the only function that ever
//! produces a different byte sequence -- and it is an explicit, opt-in
//! transformation a caller invokes deliberately.

use crate::tables::{BIDI_CONTROL, DEFAULT_IGNORABLE};

/// How strictly unannotated comment content is treated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum SecurityMode {
    /// Report unannotated occurrences as findings but do not reject them.
    ///
    /// The default is [`SecurityMode::Strict`]; this variant exists for tooling
    /// that must not fail a build.
    Lenient,
    /// Reject any unannotated occurrence, per SRC-0006.
    #[default]
    Strict,
}

/// One unannotated security-significant occurrence inside a comment.
///
/// `byte_offset` is the offset of the character *within the comment body*, so
/// a caller holding the comment's own span can map it back to a source span
/// without re-scanning.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommentSecurity {
    /// The offending code point, preserved exactly.
    pub ch: char,
    /// Byte offset within the comment body, not the source file.
    pub byte_offset: usize,
    /// The property class name, used in diagnostics.
    pub kind: &'static str,
}

impl core::fmt::Display for CommentSecurity {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(
            f,
            "{} U+{:04X} at comment byte offset {} requires a visible escaped annotation",
            self.kind, self.ch as u32, self.byte_offset
        )
    }
}

/// Returns `true` when `c` is one of the classes SRC-0006 governs.
///
/// SRC-0006 names exactly two: bidi controls and invisible format characters.
/// The implementation resolves "invisible format characters" to
/// `Default_Ignorable_Code_Point`, which is the Unicode property that defines
/// characters with no visible glyph.
fn is_comment_security_sensitive(c: char) -> bool {
    let cp = c as u32;
    crate::classify::contains(&BIDI_CONTROL, cp)
        || crate::classify::contains(&DEFAULT_IGNORABLE, cp)
}

/// Scan a comment body for unannotated security-significant characters.
///
/// `body` is the comment's content, excluding the `//`, `///`, `//!`, `/*` or
/// `*/` delimiters. Returned offsets are relative to `body`.
///
/// The scan is total: it cannot panic and it always terminates.
pub fn scan_comment_security(body: &str) -> Vec<CommentSecurity> {
    let mut out = Vec::new();
    for (offset, c) in body.char_indices() {
        if is_comment_security_sensitive(c) {
            out.push(CommentSecurity {
                ch: c,
                byte_offset: offset,
                kind: crate::classify::prohibited_kind(c)
                    .map_or("invisible format character", |k| k.as_str()),
            });
        }
    }
    out
}

/// The visible escaped annotation for `c`, using the LEX-0007 escape syntax.
///
/// The result is pure ASCII and is therefore guaranteed to be visible in any
/// terminal, editor, or log that can display the comment at all.
pub fn visible_annotation(c: char) -> String {
    format!("\\u{{{:X}}}", c as u32)
}

/// Produce an annotated copy of a comment body, replacing every
/// security-significant character with its visible escaped annotation.
///
/// This is the transformation SRC-0006 calls "generated by the formatter". It
/// is deliberately *not* applied anywhere implicitly: the lexer keeps the
/// original bytes, and only a formatter or an explicit migration tool calls
/// this function.
///
/// Annotating is idempotent for its own output. `\u{202E}` contains no
/// security-significant character, so a second pass returns the same string
/// and a formatter cannot double-escape a file it already produced.
pub fn annotate_comment(body: &str) -> String {
    let mut out = String::with_capacity(body.len());
    for c in body.chars() {
        if is_comment_security_sensitive(c) {
            out.push_str(&visible_annotation(c));
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plain_comment_has_no_findings() {
        assert!(scan_comment_security("ordinary comment text").is_empty());
    }

    #[test]
    fn bidi_control_in_comment_is_found_with_offset() {
        let found = scan_comment_security("ab\u{202E}cd");
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].ch, '\u{202E}');
        assert_eq!(found[0].byte_offset, 2, "offset is relative to the comment body");
    }

    #[test]
    fn every_bidi_control_range_is_found_in_a_comment() {
        for cp in [0x061C, 0x200E, 0x200F, 0x202A, 0x202E, 0x2066, 0x2069] {
            let c = char::from_u32(cp).expect("scalar");
            let found = scan_comment_security(&format!("x{c}y"));
            assert_eq!(found.len(), 1, "U+{cp:04X} must be found in a comment");
        }
    }

    #[test]
    fn default_ignorable_is_found_in_a_comment() {
        for cp in [0x00AD, 0x200B, 0xFEFF, 0x3164] {
            let c = char::from_u32(cp).expect("scalar");
            assert!(
                !scan_comment_security(&format!("x{c}y")).is_empty(),
                "U+{cp:04X} is an invisible format character"
            );
        }
    }

    #[test]
    fn comment_offsets_are_byte_accurate_with_multibyte_text() {
        // "e" followed by COMBINING ACUTE ACCENT occupies three bytes; the
        // security character must report its byte offset, not a char index.
        let found = scan_comment_security("e\u{301}\u{202E}");
        assert_eq!(found[0].byte_offset, 3, "byte offset, not char index");
    }

    #[test]
    fn repeated_occurrences_are_all_reported() {
        let found = scan_comment_security("\u{202E}\u{202E}\u{202E}");
        assert_eq!(found.len(), 3, "every occurrence is reported, not just the first");
    }

    #[test]
    fn annotation_is_pure_ascii_and_visible() {
        let annotated = annotate_comment("a\u{202E}b");
        assert_eq!(annotated, "a\\u{202E}b");
        assert!(annotated.is_ascii(), "an annotation must always be visible");
    }

    #[test]
    fn annotation_is_idempotent() {
        let once = annotate_comment("x\u{200B}\u{2066}y");
        let twice = annotate_comment(&once);
        assert_eq!(once, twice, "a formatter must not double-escape its own output");
    }

    #[test]
    fn annotating_then_scanning_yields_no_findings() {
        let once = annotate_comment("danger \u{202E} text");
        assert!(
            scan_comment_security(&once).is_empty(),
            "an annotated comment has nothing left to report"
        );
    }

    #[test]
    fn annotating_leaves_ordinary_comments_untouched() {
        let body = "nothing to see here";
        assert_eq!(annotate_comment(body), body);
    }

    #[test]
    fn strict_mode_is_the_default() {
        assert_eq!(SecurityMode::default(), SecurityMode::Strict);
    }

    #[test]
    fn scanning_never_panics_on_any_scalar_value() {
        for cp in 0..=0x10FFFFu32 {
            if let Some(c) = char::from_u32(cp) {
                let s = c.to_string();
                let _ = scan_comment_security(&s);
            }
        }
    }
}
